spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      #authentication-database: admin
      #username: youngjae
      #password: 123
      database: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true